# Generated by Django 3.2.5 on 2022-01-05 00:47

from babel import Locale

from django.db import migrations, models


def populate_base_lang(apps, schema_editor):
    Podcast = apps.get_model("podcasts", "Podcast")
    for podcast in Podcast.objects.all():
        temp_lang = podcast.language
        temp_lang = temp_lang.replace("-", "_")
        
        try:
            temp_locale = Locale.parse_lang(temp_lang)
            podcast.base_language = temp_locale.language
            podcast.save()
        except:
            podcast.base_language = podcast.language
            podcast.save()


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0045_auto_20191230_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='base_language',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.RunPython(populate_base_lang),
    ]
