# Generated by Django 3.2.11 on 2022-02-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0046_podcast_base_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='uses_auth',
            field=models.BooleanField(default=False),
        ),
    ]
