# Generated by Django 3.2.5 on 2022-01-05 01:12

from django.db import migrations, models
from django.utils.text import slugify


def populate_title_slug(apps, schema_editor):
    Category = apps.get_model("categories", "Category")
    for category in Category.objects.all():
        category.title_slug = slugify(category.title)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial_merged'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_slug',
            field=models.SlugField(default='', max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_title_slug),
    ]
